"""On-disk thumbnail cache.

Thumbnails are 512px (longest edge) JPEGs stored in the cache directory,
organized by the first two characters of the content hash for filesystem
friendliness.

    ~/Library/Caches/image-wizard/thumbs/ab/ab3fe...jpg
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from PIL import Image

THUMB_SIZE = 512
THUMB_QUALITY = 80

# Rotation is stored as clockwise degrees (0/90/180/270). PIL's transpose
# constants rotate *counter*-clockwise, so 90° CW == ROTATE_270, etc.
_CW_TRANSPOSE = {
    90: Image.Transpose.ROTATE_270,
    180: Image.Transpose.ROTATE_180,
    270: Image.Transpose.ROTATE_90,
}


def thumb_path(cache_dir: Path, content_hash: str) -> Path:
    return cache_dir / "thumbs" / content_hash[:2] / f"{content_hash}.jpg"


def rotated_path(cache_dir: Path, content_hash: str, degrees: int,
                 subdir: str = "thumbs") -> Path:
    """Cache path for a rotation-baked variant.

    The rotation is encoded in the filename (``…​.r90.jpg``) so a fresh
    rotation value maps to a fresh file — no stale-serve possible, and
    ``degrees=0`` never lands here (callers serve the base image instead).
    """
    return (cache_dir / subdir / content_hash[:2]
            / f"{content_hash}.r{degrees % 360}.jpg")


def ensure_rotated(base: Path, out: Path, degrees: int,
                   quality: int = THUMB_QUALITY) -> Path:
    """Bake a clockwise rotation into a JPEG derived from ``base``.

    Idempotent: returns immediately if ``out`` already exists. Used to
    serve grid thumbnails and full images with the user's manual
    rotation applied to the actual pixels (so click-through and
    copy/paste reflect it), rather than as a display-only CSS transform.
    """
    deg = degrees % 360
    if out.exists():
        return out
    im = Image.open(base)
    if im.mode not in ("RGB", "L"):
        im = im.convert("RGB")
    tr = _CW_TRANSPOSE.get(deg)
    if tr is not None:
        im = im.transpose(tr)
    out.parent.mkdir(parents=True, exist_ok=True)
    im.save(out, "JPEG", quality=quality)
    return out


def ensure_thumbnail(
    img: np.ndarray,
    cache_dir: Path,
    content_hash: str,
    force: bool = False,
) -> Path:
    """Write a thumbnail if it doesn't exist. Return the path.

    With ``force=True``, overwrite any existing cached thumbnail. Use
    this to repair thumbs that were generated by an older code path
    (e.g. before EXIF orientation handling was added to ``load_image``).
    """
    out = thumb_path(cache_dir, content_hash)
    if out.exists() and not force:
        return out

    pil = Image.fromarray(img)
    pil.thumbnail((THUMB_SIZE, THUMB_SIZE), Image.LANCZOS)
    out.parent.mkdir(parents=True, exist_ok=True)
    pil.save(out, "JPEG", quality=THUMB_QUALITY)
    return out
